### ISSUE TITLE
Client kann nicht über externe IP verbinden

### ISSUE THREAD

**Issue by profpandaa** [D3adspaceEnterprises/skylla#1]
Hey, ich wollte fragen, ob es gewollt ist, dass der Client nicht über die externe IP vom Server verbinden kann?

**Comment by felixklauke** [comment]
Darf man erfahren was das Problem war um vielleicht in Zukunft einen Hinweis zu geben?

**Comment by profpandaa** [comment]
Das Problem war: ( Weiss nicht ob das so beabsichtigt ist ) Dass man als Client nicht zu einem externen Server connecten kann ( z.b. 'n Root oder so ) d.h. es ging nur localhost
